version: '3.5'

services:
  db:
    container_name: foobooloo-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: foobooloo-db
    ports:
      - "5432:5432"
    volumes:
      - ./init/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
